name: qarinli
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_woocommerce: ^0.0.3
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1
  provider: ^4.3.2+2
  cached_network_image: ^2.3.3
  carousel_slider: ^2.3.1
  flutter_html: ^1.0.2
  url_launcher: ^5.7.10
  youtube_player_flutter: ^7.0.0+7
  flutter_rating_bar: ^3.2.0+1
  flutter_skeleton: ^0.1.0+1
  cupertino_icons: ^1.0.0
  # web_scraper: ^0.0.8
  # html: ^0.14.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  # flutter_localizations:
  #   sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/placeholder_image.png
    - assets/images_slider/
    - assets/main_categories/
    - assets/shops/

module:
  androidX: true
